config/routes.rb
require 'sidekiq/web'

Quusome::Application.routes.draw do


  root :to => "index#index"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  get "search/index"

  resources :product_items


  get "index/index"



  get "youtubes" => 'youtubes#index', :as => 'youtubes'

  post 'showcase_image' => 'showcase_images#create', :as => 'showcase_image'
  delete 'showcase_image/:id' => 'showcase_images#destroy'

  delete 'contents/:id' => 'contents#destroy'

  resources :reward_items
  resources :interest_areas
  resources :index
  resources :buy_slots

  resources :showcases do
    resources :showcase_comments, :path => 'comments'
    resources :favorites
  end



  delete 'showcase_rewards/:id' => 'showcases#showcase_rewards_destroy'

  post 'message_read_handler' => 'notifications#message_read_handler'
  post 'agent_request_read_handler' => 'notifications#agent_request_read_handler'
  post 'showcase_update_read_handler' => 'notifications#showcase_update_read_handler'
  get 'retrieve_message' => 'notifications#retrieve_message'
  get 'retrieve_agent_request' => 'notifications#retrieve_agent_request'
  get 'retrieve_showcase_update' => 'notifications#retrieve_showcase_update'

  devise_for :users, path_name: { sign_in: "login", sign_out: "logout" }, :controllers => {:sessions => 'sessions', :registrations => "registrations"}
  ActiveAdmin.routes(self)


  get 'destroy_check' => 'users#destroy_check', :as => 'destroy_check'
  get 'destroy_complete' => 'users#destroy_complete', :as => 'destroy_complete'
  #회원정보 수정
  put 'users/:id/update' => "users#update", :as => "user_update"
  get 'users/:id/update' => "users#edit", :as => "user_edit"


  resources :users do
    resources :messages, :agent_requests
    #resources :user_info
  end

  get 'user_info/:id' => 'user_info#index'
  get 'user_info/:id/modal' => 'user_info#user_info_modal', :as => 'user_info_modal'
  get 'user_info/:id/agent/:showcase_id' => 'user_info#user_info_agent_modal', :as => 'user_info_agent_modal'
  get 'user_info/:id/agent_search/:showcase_id' => 'user_info#user_info_agent_search', :as => 'user_info_agent_search'
  get 'user_info/:id/basic_info' => 'user_info#basic_info', :as => 'user_info_basic'
  get 'user_info/:id/operating_showcase' => 'user_info#operating_showcase', :as => 'user_info_operating_showcase'
  get 'user_info/:id/joining_showcase' => 'user_info#joining_showcase', :as => 'user_info_joining_showcase'
  get 'user_info/:id/favorite_showcase' => 'user_info#favorite_showcase', :as => 'user_info_favorite_showcase'
  get 'user_info/:id/agent_request' => 'user_info#agent_request', :as => 'user_info_agent_request'
  get 'user_info/:id/message' => 'user_info#message', :as => 'user_info_message'
  put 'user_info/agent_request_accept/:id' => 'user_info#agent_request_accept', :as => 'agent_request_accept'
  get 'user_info/:id/message/conversation_user' => 'user_info#conversation_user', :as => 'conversation_user'
  get 'user_info/:id/message/conversation' => 'user_info#conversation', :as => 'conversation'
  post 'user_info/:id/message' => 'user_info#message_send', :as => 'user_info_message_send'

  post 'purchase_product' => 'BuySlots#purchase_product', :as => 'purchase_product'


  #이메일 중복 체크
  get 'email_check' => 'users#email_check', :as => 'email_check'
  #아이디 중복 체크
  get 'user_id_check' => 'users#user_id_check', :as => 'user_id_check'
  get 'id_and_email_check' => 'users#id_and_email_check', :as => 'id_and_email_check'

  get 'wizard' => 'users#wizard'
  get 'inactive_sign_up' => 'users#inactive_sign_up'
  get 'active_sign_up' => 'users#active_sign_up'

  #회사소개
  get 'about' => 'about#index', :as => 'about'
  #이용약관
  get 'agreement_of_utilization' => 'about#agreement_of_utilization', :as => 'agreement_of_utilization'
  #개인정보취급방침
  get 'privacy_policy' => 'about#privacy_policy', :as => 'privacy_policy'
  get 'partnership_suggestion' => 'about#partnership_suggestion', :as => 'partnership_suggestion'

  get 'sign_up' => 'index#sign_up', :as => 'sign_up'



  post "versions/:id/revert" => "versions#revert", :as => "revert_version"



  #mobile
  namespace :mobiles do
    root :to => "index#index"
    get "showcases" => "showcases#index"
    get "showcases/:id" => "showcases#show", :as => "mobile_showcase_show"

  end


  mount Sidekiq::Web, at: '/sidekiq'





end

app/controllers/mobiles/showcases_controller.rb
class Mobiles::ShowcasesController < ApplicationController

  layout 'mobile/application'

  def index

    if params[:q].present?
      @showcases =  Showcase.publish.search(params[:q]).order('created_at desc').page(params[:page]).per(16)
    else
      @showcases = Showcase.publish.order('created_at desc').page(params[:page]).per(16)
    end

    respond_to do |format|
      format.html
    end
  end

  def show

    @showcase = Showcase.find(params[:id])

    p @showcase
    p ">>>>>>>>"

    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    p "new"
  end
end

app/controllers/showcases_controller.rb
# encoding: UTF-8

class ShowcasesController < ApplicationController

  before_filter :authenticate_user!, :except => [:index, :show]
  before_filter :user_filter, :only => [:edit, :destroy]

  impressionist :actions => [:show]
  # GET /showcases
  # GET /showcases.json
  def index

    if params[:q].present?
      @showcases =  Showcase.publish.search(params[:q]).order('created_at desc').page(params[:page]).per(16)
    else
      @showcases = Showcase.publish.order('created_at desc').page(params[:page]).per(16)
    end

    #@activities = PublicActivity::Activity.order("created_at DESC").all


    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @showcases }
    end
  end

  # GET /showcases/1
  # GET /showcases/1.json
  def show


    @showcase = Showcase.find(params[:id])
    @comment_threads = @showcase.comment_threads.order('created_at desc')
    session[:return_to] = "/showcases/#{params[:id]}"

    respond_to do |format|
      if @showcase.is_publish == '1'
        format.html
      else
        if current_user and current_user.id == @showcase.created_by
          format.html
        else
          format.html { render :template => "showcases/show_private" }
        end


      end

    end
  end

  # GET /showcases/new
  # GET /showcases/new.json
  def new


    @showcase = Showcase.new
    @reward_items = RewardItem.where(:location => I18n.locale.to_s.upcase)


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @showcase }
    end
  end

  # GET /showcases/1/edit
  def edit
    @showcase = Showcase.find(params[:id])
    @reward_items = RewardItem.all
    #ShowcaseUpdateWorker.perform_async(params[:id], current_user.id)
  end

  # POST /showcases
  # POST /showcases.json
  def create
    @showcase = Showcase.new(params[:showcase]) do |showcase|
      showcase.created_by = current_user.id
      showcase.updated_by = current_user.id
    end

    #notice = '쇼케이스가 성공적으로 저장되었습니다. 친구에게 초대메세지를 보내보세요.'
    respond_to do |format|
      if @showcase.save
        format.html { redirect_to @showcase, notice: notice }
        format.json { render json: @showcase, status: :created, location: @showcase }
      else
        format.html { render action: "new" }
        format.json { render json: @showcase.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /showcases/1
  # PUT /showcases/1.json
  def update
    @showcase = Showcase.find(params[:id])

    @showcase.contents.destroy_all

    respond_to do |format|
      if @showcase.update_attributes(params[:showcase])
        format.html { redirect_to @showcase, notice: '쇼케이스가 성공적으로 수정되었습니다.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @showcase.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /showcases/1
  # DELETE /showcases/1.json
  def destroy
    @showcase = Showcase.find(params[:id])

    if @showcase.agent_contracts.working_agent.count == 0

    #업로드된 이미지 삭제
      @showcase.contents.each do |content|
        if content.source_type == 'upload'
          showcase_image = ShowcaseImage.where(:id => content.showcase_image_id).first
          showcase_image.destroy if showcase_image.present?
        end
      end
      @showcase.destroy
      info = "쇼케이스가 성공적으로 삭제되었습니다."
      flash[:info] = info
    else
      warning = "계약된 에이전트가 있습니다. 계약이 끝난 후 삭제해주세요."
      flash[:warning] = warning
    end


    respond_to do |format|
      format.html { redirect_to user_info_operating_showcase_path(current_user) }
      format.json { head :no_content }
    end
  end

  def showcase_rewards_destroy
    @showcase_reward = ShowcaseReward.find(params[:id])
    @showcase_reward.destroy

    head :ok
  end

  def user_filter
    showcase = Showcase.find(params[:id])
    unless showcase.user == current_user
      redirect_to showcase, notice: "수정이나 삭제 권한이 없습니다."
    end

  end
end

app/helpers/showcases_helper.rb
module ShowcasesHelper
  def reward_item


  end
end

app/views/showcases/form/_image_upload_modal.html.erb
<div id="ImageModal" class="modal hide fade" tabindex="-1" role="dialog" data-height="500px" data-backdrop="static" aria-labelledby="ImageModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h5 id="ImageModalLabel"><%= t(:'showcase.registration.content.image_modal.head') %></h5>
  </div>
  <div class="modal-body">
    <div id="image_spin" style="display:none;"></div>
    <p style="font-size: 11px;"><%= t(:'showcase.registration.content.image_modal.description') %>
    <span class="image_upload_add_btn">
      <input type="button" id="image_upload_add_btn" class="btn" value="<%=t(:'showcase.registration.content.image_modal.add_button') %>" style="margin-top: 10px; margin-left: 480px;">
    </span>
    </p>
    <%= form_tag showcase_image_path, :multipart => true, :remote => true do  %>
        <div class="image_upload_div" style="height:400px; overflow-y:auto; overflow-x: hidden;">

            <div class="image_upload_row">
                <div class="image_type">

                  <label><input type="radio" name="showcase_images[0][type]" class="image_upload_radio" checked="checked" value="upload"> <span><%= t(:'showcase.registration.content.image_modal.check_upload') %></span></label>
                  <label><input type="radio" name="showcase_images[0][type]" class="image_upload_radio"  value="url"> <span><%= t(:'showcase.registration.content.image_modal.check_url') %></span></label>
                </div>
                <div class="image_upload" style="width:510px; height:20px; background-color: #e9eaea; padding:10px;">
                  <input type="file" name="showcase_images[0][image]" style="line-height: 10px; font-size: 12px;">
                </div>

                <div class="image_url" style="width:510px; height:20px; background-color: #e9eaea; padding:10px; display: none;">
                    URL : <input type="text" name="showcase_images[0][url]" style="line-height: 0px; font-size: 12px;">
                </div>

                <div style="width:530px; background-color: #e9eaea; " class="image_desc">
                  <span style="margin-left: 10px; margin-top: 5px;"><%= t(:'showcase.registration.content.image_modal.explain_label') %> : <textarea name="showcase_images[0][caption]" rows="1" style="width:440px"></textarea> </span>
                </div>

                <div style="width:530px; background-color: #e9eaea; " class="image_desc">
                  <span style="margin-left: 10px;"><%= t(:'showcase.registration.content.image_modal.link_label') %> : <input type="text" name="showcase_images[0][link]" style="width:410px"/> </span>
                </div>
            </div>
        </div>


        <input type="submit" id="showcase_image_upload_submit" style="display: none">
    <% end %>


  </div>
  <div class="modal-footer">
    <button class="btn btn-primary" style="" type="button" id="showcase_image_upload_btn"><%= t(:'showcase.registration.content.image_modal.save_button') %></button>
    <button class="btn" data-dismiss="modal" style="" type="button" id="showcase_image_close_btn"><%= t(:'showcase.registration.content.image_modal.close_button') %></button>
  </div>
</div>

app/views/showcases/form/_showcase_agent_mission.html.erb
<p xmlns="http://www.w3.org/1999/html"></p>
<p style="font-size: 15px;"><b>5. 에이전트 미션</b></p>

<%= f.select :mission_term, [["#{t(:"showcase.registration.mission.term_select")}",''],
                             ["07#{t(:"showcase.registration.mission.day")}",'07'],
                             ["14#{t(:"showcase.registration.mission.day")}",'14'],
                             ["21#{t(:"showcase.registration.mission.day")}",'21'],
                             ["28#{t(:"showcase.registration.mission.day")}",'28']], {},  { :class => "selectpicker span4"} %>


<P></P>
<%= f.text_area :mission_info, :rows => 5, :placeholder => "에이전트에게 요청할 미션에 대한 추가 설명을 해주세요.", :style => "width: 360px; font-size: 12px;"%>

<p style="font-size: 12px;"><%= raw t(:"showcase.registration.mission.mission_description_placeholder") %></p>

<div class="btn-group" style="text-align: center;">
  <input type="hidden" id="selected_reward_count" value="0">
  <% @reward_items.in_groups_of(6, false) do |items| %>
    <% items.each do |item| %>
          <a  class="btn example btn-large" rel="clickover"  data-placement="left" id="reward_<%= item.id %>"
              data-id="#reward-<%= item.id %>" data-original-title="<%= item.title %>"
              style="font-size: 14px; width: 48px; height:48px; padding:2px; margin: 4px;"
          >

            <%= image_tag "48x48/#{item.image}" %></a>

          <div id="reward-<%= item.id %>" style="display: none;" >
            <p style="font-size: 12px;"><%= item.description %></p>
            <textarea rows="3" style="width:190px; height: 60px; font-size: 11px"></textarea>
            <div style="text-align: right;">
              <a class="btn btn-primary agent_save_btn"
                 reward_item_id="<%= item.id %>" reward_item_image="<%= item.image %>" ><%= t(:"showcase.registration.mission.mission_save_button") %></a>
              <a class="btn reward_close_btn" id="close_<%= item.id %>" data-dismiss="clickover"><%= t(:"showcase.registration.mission.mission_close_button") %></a>
            </div>
          </div>

    <% end %>
        </br>
  <% end %>
</div>


<p></p>

<div class="SelectReward" style="height:115px; background-color: #b7b8b8; padding: 5px;">
  <div class="row-fluid">
    <ul class="thumbnails selected_rewards">
      <% f.object.showcase_rewards.each do |showcase_reward| %>

          <li style="margin-left: 5px; margin-bottom: 5px; display: list-item;" class="seleted_reward">
            <input type="hidden" class="reward_item_id" value="">
            <input type="hidden" value="<%= showcase_reward.detail_info %>">
            <input type="hidden" class="showcase_reward_id" value="<%=showcase_reward.id %>" />
            <a style="cursor: pointer" class="thumbnail">
                <img src="/assets/45x45/<%= showcase_reward.reward_item.image %>">
            </a>
          </li>
      <% end %>

    </ul>
  </div>
</div>

app/views/showcases/form/_showcase_contents.html.erb
<div class="ContentRegis" style="float: left; width: 373px; height: 670px; background-color: #dadcdc; padding: 10px;"> <!----Contents Register START----------->
<p></p>
<p style="font-size: 15px;"><b>4. <%= t(:'showcase.registration.content.registration') %></b></p>

<!------------사진찾기 MODAL START------------------->
<a href="#ImageModal" role="button" class="btn btn-large btn-danger" data-toggle="modal" style="font-size: 14px; width: 330px;"><%= t(:'showcase.registration.content.image_find_button') %></a>


<!------------사진찾기 MODAL END------------------->
<p></p>

<p></p>

<!------------동영상 MODAL START------------------->
<a href="#VideoModal" role="button" class="btn btn-large btn-success" data-toggle="modal" style="font-size: 14px; width: 330px;"><%= t(:'showcase.registration.content.video_find_button') %></a>


<!------------동영상 MODAL END------------------->
<p></p>


<hr>
<div class="tabbable" style="margin-bottom: 18px;">


  <div class="tab-content " style="padding-left: 10px; padding-right: 10px; border-bottom: 1px solid #ddd;  z-index: 9999;">
    <div class="tab-pane active nano" id="tab1" style="height:450px;  background-color: #b7b8b8; padding-top: 10px;">
      <div class="row-fluid  content" >

        <input type="hidden" id="last_count" value="0">

            <ul class="thumbnails" id="image_upload_thumb">
              <% f.object.contents.each_with_index do |content, i| %>
                <% if content.source_type == 'upload' or content.source_type == 'url' %>
                  <li class="upload_image thumbnail_content">
                    <div style="display: none" class="thumbnails_icon">
                      <div class="icon_move"><i class="icon-move"></i></div>
                      <div class="icon_modify"><i class="icon-pencil"></i></div>
                      <div class="icon_remove"><i class="icon-remove-sign"></i></div>
                    </div>

                      <img src="<%= content.url %>" style="width:140px; height:110px"  class="register_thumb">
                    <input type="hidden" name="index" id="thumbnail_index_<%= i %>" class="thumbnail_index" />
                    <input type="hidden" name="showcase[contents_attributes][<%= i %>][source_type]" class="source_type" value="<%= content.source_type %>"/>
                    <input type="hidden" name="showcase[contents_attributes][<%= i %>][caption]" class="caption" value="<%= content.caption %>" />
                    <input type="hidden" name="showcase[contents_attributes][<%= i %>][showcase_image_id]" class="showcase_image_id" value="<%= content.showcase_image_id %>" />
                    <input type="hidden" name="showcase[contents_attributes][<%= i %>][url]" class="url" value="<%= content.url %>" />
                    <input type="hidden" name="showcase[contents_attributes][<%= i %>][link]" class="link" value="<%= content.link %>" >
                    <!--<input type="hidden" class="content_id" value="<%= content.id %>" />-->
                  </li>
                <% else %>
                      <li class="video_upload thumbnail_content" style="">

                        <div class="background_play" ></div>
                        <div style="display: none" class="thumbnails_icon">
                          <div class="icon_move"><i class="icon-move"></i></div>

                          <div class="icon_remove"><i class="icon-remove-sign"></i></div>
                        </div>



                            <img src="http://img.youtube.com/vi/<%= content.source_id %>/1.jpg" style="width:140px; height:110px;" class="register_thumb">

                        <input type="hidden" name="showcase[contents_attributes][<%= i %>][source_type]" class="source_type" value="<%= content.source_type %>"/>
                        <input type="hidden" name="showcase[contents_attributes][<%= i %>][caption]" class="caption" value="<%= content.caption %>" />
                        <input type="hidden" name="showcase[contents_attributes][<%= i %>][source_id]" class="source_id" value="<%= content.source_id %>" />
                        <!--<input type="hidden" name="showcase[contents_attributes][<%= i %>][showcase_image_id]" class="showcase_image_id" value="<%= content.showcase_image_id %>" />-->
                        <input type="hidden" name="showcase[contents_attributes][<%= i %>][url]" class="url" value="<%= content.url %>" />


                      </li>
                <% end %>
              <% end %>

            </ul>

      </div>
    </div>



  </div>
</div>

</div>   <!----Contents Register END----------->

app/views/showcases/form/_showcase_info.html.erb
<div class="BasicRegis" style="float: left; width: 373px; height: 670px; background-color: #e9eaea; padding: 10px;">
  <p></p>
  <p style="font-size: 15px;"><b>1. <%= t(:'showcase.registration.info.title') %></b></p>
  <%= f.text_field :title, :style => 'width: 350px; font-size: 12px;', :placeholder => "#{t(:'showcase.registration.info.title_placeholder')}" %></hr>

  <p style="font-size: 15px;"><b>2. <%= t(:"showcase.registration.info.explanation") %></b></p>
  <%= f.text_area :info, :rows => 6, :style => 'width: 350px; font-size: 12px;', :placeholder => "#{t(:'showcase.registration.info.explanation_placeholder')}" %>

  <p></p>



  <hr style="margin-top: 50px;">
  <p style="font-size: 15px;"><b>3. <%= t(:'showcase.registration.info.config') %></b></p>
  <p style="display: none">
    <label class="checkbox">
        <%= f.check_box :only_invite  %> <%= t(:'showcase.registration.info.config_only_invite') %>
    </label>
  </p>
  <br/>
  <p>
    <label class="checkbox">
        <%= f.check_box :reject_message  %> <%= raw t(:'showcase.registration.info.config_reject_message') %>
    </label>
  </p>
</div>

app/views/showcases/form/_video_upload_modal.html.erb
<div id="VideoModal" class="modal hide fade" tabindex="-1" data-width="1000px" data-height="500px" data-backdrop="static" role="dialog" aria-labelledby="VideoModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h5 id="VideoModalLabel"><%= t(:'showcase.registration.content.video_modal.head') %></h5>
  </div>
  <div class="modal-body" style="height:500px; max-height: 400px;">

    <div class="grid1" style="float: left; width: 400px; height: 390px; background-color: #e9eaea; padding: 5px; margin-left: 5px; font-size: 12px;">
      <div id="youtube_preview_div" style="float: left; width: 387px; height: 260px; background-color: black; padding: 3px; margin: 3px;">

      </div>
      <div class="mgzcrop3" style="float: left; width: 387px; height: 75px; padding: 3px; margin: 3px;">
        <textarea rows="3" id="youtube_source" placeholder="<%= t(:'showcase.registration.content.video_modal.textarea_placeholder') %>" style="width: 373px; height: 65px; font-size: 12px;"></textarea>
      </div>
      <div class="mgzcrop3" style="float: left; width: 387px; height: 18px; padding: 3px; margin: 3px; text-align: right">
        <button class="btn btn-mini btn-inverse" type="button" id="youtube_preview_text_btn"><%= t(:'showcase.registration.content.video_modal.preview_button') %></button>
      </div>
    </div>

    <div class="grid2" style="float: left; width: 535px; height: 390px; background-color: #e9eaea; padding: 5px; margin-left: 5px;">
      <%= form_tag youtubes_path, :method => 'get', :remote => true do %>
          <div class="mgzcrop3" style="float: left; width: 523px; height: 30px; padding: 3px; margin: 3px; text-align: right;">
            <input type="text" class="search-query span2"  id="youtube_query" name="youtube_query"
                   placeholder="YouTube&nbsp;&nbsp;Search" style="width:200px; font-size: 12px;">
            <input type="text" name="dummy" style="display: none;">
            <input type="hidden" id="youtube_page" name="youtube_page" value="1">
            <input type="submit" id="youtube_submit" style="display: none">
          </div>
      <% end %>
      <div id="spin" style="display:none;"></div>
      <div class="mgzcrop3" id="youtube_search_result_div" style="float: left; width: 523px; height: 305px; padding: 3px; margin: 3px; overflow-y: scroll">
        <input type="hidden" id="youtube_hidden_id">
        <input type="hidden" id="youtube_hidden_image_url">
        <input type="hidden" id="is_loading" value="false">
        <table class="table table-hover" style="background-color: white;">

          <tbody id="youtube_body">


          </tbody>
        </table>

      </div>
      <div class="mgzcrop3" style="float: left; width: 523px; height: 18px; padding: 3px; margin: 3px; text-align: right">
        <button class="btn btn-mini btn-inverse" type="button" id="youtube_preview_btn"><%= t(:'showcase.registration.content.video_modal.preview_button') %></button>
      </div>

    </div>




  </div>
  <div class="modal-footer">
    <button class="btn btn-primary" id="youtube_save_btn">저장하기</button>
    <button class="btn" data-dismiss="modal" aria-hidden="true" id="youtube_close_btn">닫기</button>
  </div>
</div>